#!/usr/bin/env perl

use strict;
use warnings;

use File::Basename;

my $usage = "usage: $0 sampleA.RSEM.isoform.results sampleB.RSEM.isoform.results ...\n\n";

unless (@ARGV) {
    die $usage;
}

my @rsem_files = @ARGV;

unless (scalar @rsem_files > 1) {
    die $usage;
}

main: {


    my %data;
    my @name=@rsem_files;
    for(my $i=0;$i<@rsem_files;$i++){
	$name[$i]=basename($name[$i]);
	$name[$i]=~s/.Readcount_FPKM.xls$//;
   }

    foreach my $file (@rsem_files) {
        
        open (my $fh, $file) or die "Error, cannot open file $file";
	<$fh>;
        while (<$fh>) {
            chomp;
            my ($acc,$sname, $count, $rpkm) = split(/\t/);
            $data{$acc}->{$file} = $rpkm;
        }
        close $fh;
    }

    my @filenames = @rsem_files;
    foreach my $file (@filenames) {
        $file = basename($file);
    }

    print "gene_id"; 
    print join("\t", "", @name) . "\n";
    foreach my $acc (keys %data) {
        
        print "$acc";

        foreach my $file (@rsem_files) {

            my $count = $data{$acc}->{$file};
            unless (defined $count) {
                $count = "NA";
            }

            print "\t$count";
            
        }
        
        print "\n";
        
    }
    
    
    exit(0);
}
    
        
